fix: Reduce concurrency of all AWS task
To combat:

```
Exit code: 1
OutOfMemoryError: Container killed due to memory usage
```

See https://www.cloudquery.io/docs/advanced-topics/performance-tuning#tune-concurrency.