fix: Reduce concurrency of EC2, lambda, and S3 tasks
To combat their greedy memory usage causing AWS to terminate them:

```
Exit code: 1
OutOfMemoryError: Container killed due to memory usage
```