fix: Regenerate `package-lock.json`
There is a `tsc` error:

```
Error: [typecheck] node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(2527,55): error TS2339: Property 'POST /repos/{owner}/{repo}/pages/deployment' does not exist on type 'Endpoints'.
Error: [typecheck] node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(2528,33): error TS2339: Property 'POST /repos/{owner}/{repo}/pages/deployment' does not exist on type 'Endpoints'.
```

The suggestion from https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/172 is this is caused by a transitive dependency version being incompatible.

Below is the result of a diff when running `npm ls --all | grep octokit` against the previous `package-lock.json`.
It shows the following updates to transitive dependencies:
- `@octokit/endpoint` from 9.0.4 to 9.0.5
- `@octokit/types` from 12.6.0 to 13.4.1
- `@octokit/request` from 9.0.1 to 9.1.1
- `@octokit/request-error` from 6.0.2 to 6.1.1
- `@octokit/core` from 5.0.2 to 5.2.0
- `@octokit/openapi-types` is removed
- `@octokit/app` from 14.0.2 to 14.1.0
- `@octokit/oauth-app` from 6.0.0 to 6.1.0
- `@octokit/plugin-paginate-rest` from 9.1.5 to 9.2.1
- `@octokit/webhooks` from 12.0.10 to 12.2.0
- `@octokit/webhooks-methods` from 4.0.0 to 4.1.0
- `@octokit/webhooks-types` from 7.1.0 to 7.4.0
- `@octokit/graphql` from 7.0.2 to 7.1.0
- `@octokit/plugin-paginate-graphql` from 4.0.0 to 4.0.1
- `@octokit/plugin-rest-endpoint-methods` from 10.2.0 to 10.4.1
- `@octokit/plugin-throttling` from 8.1.3 to 8.2.0

```diff
22,24c22,23
< │ │ │ ├─┬ @octokit/endpoint@9.0.4
< │ │ │ │ ├─┬ @octokit/types@12.6.0
< │ │ │ │ │ └── @octokit/openapi-types@20.0.0
---
> │ │ │ ├─┬ @octokit/endpoint@9.0.5
> │ │ │ │ ├── @octokit/types@13.4.1 deduped
29,37c28,33
< │ │ ├─┬ @octokit/request@9.0.1
< │ │ │ ├─┬ @octokit/endpoint@10.0.0
< │ │ │ │ ├─┬ @octokit/types@12.6.0
< │ │ │ │ │ └── @octokit/openapi-types@20.0.0
< │ │ │ ├─┬ @octokit/request-error@6.0.2
< │ │ │ │ └─┬ @octokit/types@12.6.0
< │ │ │ │   └── @octokit/openapi-types@20.0.0
< │ │ │ ├─┬ @octokit/types@12.6.0
< │ │ │ │ └── @octokit/openapi-types@20.0.0
---
> │ │ ├─┬ @octokit/request@9.1.1
> │ │ │ ├─┬ @octokit/endpoint@10.1.1
> │ │ │ │ ├── @octokit/types@13.4.1 deduped
> │ │ │ ├─┬ @octokit/request-error@6.1.1
> │ │ │ │ └── @octokit/types@13.4.1 deduped
> │ │ │ ├── @octokit/types@13.4.1 deduped
45c41
< │ │ ├─┬ @octokit/app@14.0.2
---
> │ │ ├─┬ @octokit/app@14.1.0
51,53c47,49
< │ │ │ ├── @octokit/core@5.0.2 deduped
< │ │ │ ├── @octokit/oauth-app@6.0.0 deduped
< │ │ │ ├── @octokit/plugin-paginate-rest@9.1.5 deduped
---
> │ │ │ ├── @octokit/core@5.2.0 deduped
> │ │ │ ├── @octokit/oauth-app@6.1.0 deduped
> │ │ │ ├── @octokit/plugin-paginate-rest@9.2.1 deduped
56c52
< │ │ │ └─┬ @octokit/webhooks@12.0.10
---
> │ │ │ └─┬ @octokit/webhooks@12.2.0
58,60c54,56
< │ │ │   ├── @octokit/webhooks-methods@4.0.0
< │ │ │   ├── @octokit/webhooks-types@7.1.0
< │ │ ├─┬ @octokit/core@5.0.2
---
> │ │ │   ├── @octokit/webhooks-methods@4.1.0
> │ │ │   ├── @octokit/webhooks-types@7.4.0
> │ │ ├─┬ @octokit/core@5.2.0
62c58
< │ │ │ ├─┬ @octokit/graphql@7.0.2
---
> │ │ │ ├─┬ @octokit/graphql@7.1.0
64c60
< │ │ │ │ ├── @octokit/types@12.6.0 deduped
---
> │ │ │ │ ├── @octokit/types@13.4.1 deduped
67,69c63,64
< │ │ │ ├─┬ @octokit/types@12.6.0
< │ │ │ │ └── @octokit/openapi-types@20.0.0
< │ │ ├─┬ @octokit/oauth-app@6.0.0
---
> │ │ │ ├── @octokit/types@13.4.1 deduped
> │ │ ├─┬ @octokit/oauth-app@6.1.0
73c68
< │ │ │ ├── @octokit/core@5.0.2 deduped
---
> │ │ │ ├── @octokit/core@5.2.0 deduped
76,79c71,74
< │ │ ├─┬ @octokit/plugin-paginate-graphql@4.0.0
< │ │ │ └── @octokit/core@5.0.2 deduped
< │ │ ├─┬ @octokit/plugin-paginate-rest@9.1.5
< │ │ │ ├── @octokit/core@5.0.2 deduped
---
> │ │ ├─┬ @octokit/plugin-paginate-graphql@4.0.1
> │ │ │ └── @octokit/core@5.2.0 deduped
> │ │ ├─┬ @octokit/plugin-paginate-rest@9.2.1
> │ │ │ ├── @octokit/core@5.2.0 deduped
82,83c77,78
< │ │ ├─┬ @octokit/plugin-rest-endpoint-methods@10.2.0
< │ │ │ ├── @octokit/core@5.0.2 deduped
---
> │ │ ├─┬ @octokit/plugin-rest-endpoint-methods@10.4.1
> │ │ │ ├── @octokit/core@5.2.0 deduped
87c82
< │ │ │ ├── @octokit/core@5.0.2 deduped
---
> │ │ │ ├── @octokit/core@5.2.0 deduped
91,92c86,87
< │ │ ├─┬ @octokit/plugin-throttling@8.1.3
< │ │ │ ├── @octokit/core@5.0.2 deduped
---
> │ │ ├─┬ @octokit/plugin-throttling@8.2.0
> │ │ │ ├── @octokit/core@5.2.0 deduped
```