Revert "chore(deps): Bump react-router-dom from 5.3.3 to 6.24.1"
This reverts commit 17a27d50ce84c92a686929d1b640ac0acd2d09a0.

Version 6.24.1 breaks the `dashboard` project with:

```log
Error: ../../node_modules/@types/react-router-dom/index.d.ts(13,10): error TS2724: '"react-router"' has no exported member named 'match'. Did you mean 'UIMatch'?
Error: ../../node_modules/@types/react-router-dom/index.d.ts(19,5): error TS2305: Module '"react-router"' has no exported member 'PromptProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(20,5): error TS2305: Module '"react-router"' has no exported member 'Prompt'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(23,5): error TS2305: Module '"react-router"' has no exported member 'RedirectProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(24,5): error TS2724: '"react-router"' has no exported member named 'Redirect'. Did you mean 'redirect'?
Error: ../../node_modules/@types/react-router-dom/index.d.ts(25,5): error TS2305: Module '"react-router"' has no exported member 'RouteChildrenProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(26,5): error TS2305: Module '"react-router"' has no exported member 'RouteComponentProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(31,5): error TS2305: Module '"react-router"' has no exported member 'StaticRouterProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(32,5): error TS2305: Module '"react-router"' has no exported member 'StaticRouter'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(33,5): error TS2305: Module '"react-router"' has no exported member 'SwitchProps'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(34,5): error TS2305: Module '"react-router"' has no exported member 'Switch'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(35,5): error TS2724: '"react-router"' has no exported member named 'match'. Did you mean 'UIMatch'?
Error: ../../node_modules/@types/react-router-dom/index.d.ts(37,5): error TS2305: Module '"react-router"' has no exported member 'withRouter'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(38,5): error TS2305: Module '"react-router"' has no exported member 'RouterChildContext'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(39,5): error TS2305: Module '"react-router"' has no exported member 'useHistory'.
Error: ../../node_modules/@types/react-router-dom/index.d.ts(42,5): error TS2724: '"react-router"' has no exported member named 'useRouteMatch'. Did you mean 'RouteMatch'?
```

Indeed, upgrading from v5 to v6 is detailed here - https://reactrouter.com/en/main/upgrading/v5.