Increase resources for `GithubTeams` task (#535)
This task is being killed by AWS with the reason:

```
OurOFMemoryError: Container killed due to memory usage
```

Increase the resources, to resolve.

Note, the new values were selected somewhat arbitrarily!

Co-authored-by: Ashleigh <AshCorr@users.noreply.github.com>
Co-authored-by: Natasha <NovemberTang@users.noreply.github.com>
Co-authored-by: Thalia <tjsilver@users.noreply.github.com>
Co-authored-by: Akash <akash1810@users.noreply.github.com>